name: Test Secrets
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - env:
        KEY: ${{ secrets.TRELLO_KEY }}
        BOARD: ${{ secrets.BOARD_ID }}
      run: |
        echo "KEY: ${KEY:0:4}..."
        echo "BOARD: $BOARD"
